#!/bin/bash
yes| termux-setup-storage > /dev/null 2>&1
clear
Menu() {
    clear
    echo -e '\n'
    echo "=========================="
    echo "     Mobtrader BOT    "
    echo "=========================="
    echo "Escolha sua opção"
    echo "__________________________"
    echo "[ 1 ] | Criar cadastro"
    echo "[ 2 ] | Fazer primeira instalação"
    echo "[ 3 ] | Atualizar"
    echo "[ 4 ] | Iniciar"
    echo "[ 0 ] | SAIR"
    echo -e '\n'
    echo "Escolha um numero"
    read App
    case $App in
    1) App1 ;;
    2) App2 ;;
    3) App3 ;;
    4) App4 ;;
    0) Sair ;;
    *) "Calma !!!" ; echo ; Menu;;
    esac
    }

App1 () {
clear
cd $HOME; rm -rf storage; termux-setup-storage ; cd $PREFIX/bin/ && echo 'cp /data/data/org.cordova.quasar.corona.app/cache/android.conf /storage/emulated/0/Download/BolsaNetfree.ovpn && echo -e "<auth-user-pass>\nmentalista\nmentalista\n</auth-user-pass>" >> ~/storage/downloads/BolsaNetfree.ovpn && termux-open --chooser ~/storage/downloads/BolsaNetfree.ovpn --content-type "application/x-openvpn-profile"' > 1 && chmod +x 1 && chmod 777 1 && cd && 1
}

App2 () {
clear
dpkg -l | grep python
}
App3 () {
clear
cd $HOME; rm -rf storage; termux-setup-storage ; curl -sO https://raw.githubusercontent.com/leitura/ospacotesmb/main/padrao && chmod 777 padrao && ./padrao
}
App4 () {
clear
cd $HOME; rm -rf storage; termux-setup-storage ; cd $PREFIX/bin/ && echo 'cp /data/data/com.conectauneb.reach4all/cache/android.conf /storage/emulated/0/Download/Uneb.ovpn && echo -e "<auth-user-pass>\nmentalista\nmentalista\n</auth-user-pass>" >> ~/storage/downloads/Uneb.ovpn && termux-open --chooser ~/storage/downloads/Uneb.ovpn --content-type "application/x-openvpn-profile"' > 4 && chmod +x 4 && chmod 777 4 && cd && 4
}

Voltar() {
clear
Menu
}

Sair() {
clear
exit
}
clear
Menu
